AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Test local deployment of Lambda function
Resources:
  ScrapeIdealistaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Test local deployment of Lambda function
      Runtime: python3.10
      Handler: lambda_function.lambda_handler
      CodeUri: ./func_scrape_idealista
      Policies:
        - "AWSConfigRulesExecutionRole"
        - "AWSLambdaDynamoDBExecutionRole"
      MemorySize: 128
      Timeout: 5
  
  SharedResourcesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
          LayerName: shared_layer
          Description: Dependencies for sam lambda functions
          ContentUri: ./lambda_layers/python
          CompatibleRuntimes:
            - python3.10

  MyTable:
     Type: AWS::Serverless::SimpleTable