AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Test local deployment of Lambda function
Resources:
  ScrapeIdealistaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Test local deployment of Lambda function
      Runtime: python3.10
      Handler: lambda_function.lambda_handler
      CodeUri: func_scrape_idealista/.
      Policies:
        - "AWSConfigRulesExecutionRole"
        - "AWSLambdaDynamoDBExecutionRole"
      MemorySize: 128
      Timeout: 300
      Layers:
        - !Ref SharedResourcesLayer

  SharedResourcesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared_modules
      Description: Dependencies for SAM lambda functions
      ContentUri: my_layer/.
      CompatibleRuntimes:
        - python3.10
